# Generated by Django 3.2.3 on 2021-06-22 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='personal_ad',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
