# Generated by Django 3.2.3 on 2021-06-25 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_profile_email_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email_confirmed',
        ),
    ]
