# Generated by Django 5.2.1 on 2025-05-26 02:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_fcmtoken_devices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
