# Generated by Django 5.2.1 on 2025-06-10 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_alter_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispositivoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_inventario', models.CharField(max_length=50, unique=True)),
                ('tipo', models.CharField(choices=[('computadora', 'Computadora'), ('movil', 'Móvil'), ('tablet', 'Tablet'), ('otro', 'Otro')], max_length=20)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=100)),
                ('serial', models.CharField(max_length=50, unique=True)),
                ('ubicacion', models.CharField(max_length=100)),
                ('fecha_adquisicion', models.DateField()),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('en_reparacion', 'En reparación'), ('baja', 'Baja')], max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos_creados', to=settings.AUTH_USER_MODEL)),
                ('usuario_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispositivos_asignados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dispositivo de Inventario',
                'verbose_name_plural': 'Dispositivos de Inventario',
                'db_table': 'dispositivos_inventario',
            },
        ),
    ]
