# Generated by Django 5.2.1 on 2025-06-10 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_dispositivoinventario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispositivoinventario',
            name='usuario_asignado',
        ),
        migrations.AddField(
            model_name='dispositivoinventario',
            name='responsable',
            field=models.CharField(default='Sin Asignar', max_length=100),
        ),
        migrations.AlterField(
            model_name='dispositivoinventario',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('En reparación', 'En reparación'), ('Baja', 'Baja')], max_length=20),
        ),
        migrations.AlterField(
            model_name='dispositivoinventario',
            name='marca',
            field=models.CharField(choices=[('Dell', 'Dell'), ('HP', 'HP'), ('Lenovo', 'Lenovo'), ('Apple', 'Apple'), ('Asus', 'Asus'), ('Acer', 'Acer'), ('Otro', 'Otro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='dispositivoinventario',
            name='tipo',
            field=models.CharField(choices=[('computadora', 'Computadora'), ('movil', 'Móvil'), ('telefono_fijo', 'Teléfono Fijo'), ('impresora', 'Impresora'), ('router', 'Router'), ('switcher', 'Switcher'), ('otro', 'Otro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='dispositivoinventario',
            name='ubicacion',
            field=models.CharField(choices=[('Departamento de Sistema', 'Departamento de Sistema'), ('Gerencia Financiera', 'Gerencia Financiera'), ('Seguridad y Proteccion', 'Seguridad y Protección'), ('Atención al hombre', 'Atención al hombre'), ('Auditoria', 'Auditoría')], max_length=50),
        ),
        migrations.AlterModelTable(
            name='dispositivoinventario',
            table=None,
        ),
    ]
