# Generated by Django 5.2.1 on 2025-06-10 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_remove_dispositivoinventario_usuario_asignado_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dispositivoinventario',
            options={'managed': True, 'verbose_name': 'Dispositivo de Inventario', 'verbose_name_plural': 'Dispositivos de Inventario'},
        ),
        migrations.AlterModelTable(
            name='dispositivoinventario',
            table='dispositivos_inventario',
        ),
    ]
