# Generated by Django 5.2.1 on 2025-06-11 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_alter_dispositivoinventario_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('completo', 'Completo'), ('diferencial', 'Diferencial'), ('incremental', 'Incremental')], max_length=20)),
                ('descripcion', models.CharField(max_length=255)),
                ('tamaño', models.BigIntegerField()),
                ('ubicacion', models.CharField(max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backups_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Backup',
                'verbose_name_plural': 'Backups',
                'db_table': 'backup',
            },
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('preventivo', 'Preventivo'), ('correctivo', 'Correctivo')], max_length=20)),
                ('estado', models.CharField(choices=[('programado', 'Programado'), ('en_proceso', 'En Proceso'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='programado', max_length=20)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('fecha_programada', models.DateTimeField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('realizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mantenimientos_realizados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mantenimiento',
                'verbose_name_plural': 'Mantenimientos',
                'db_table': 'mantenimiento',
            },
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_reporte', models.CharField(choices=[('inventario', 'Inventario'), ('actividad', 'Actividad'), ('mantenimiento', 'Mantenimiento'), ('incidencia', 'Incidencia')], max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.JSONField()),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('ruta_archivo', models.CharField(blank=True, max_length=255, null=True)),
                ('generado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_generados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
                'db_table': 'reporte',
            },
        ),
        migrations.CreateModel(
            name='AsignacionDispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_devolucion', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='users.dispositivoinventario')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos_asignados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asignación de Dispositivo',
                'verbose_name_plural': 'Asignaciones de Dispositivos',
                'db_table': 'asigna',
                'unique_together': {('dispositivo', 'usuario')},
            },
        ),
        migrations.CreateModel(
            name='DispositivoMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='users.dispositivoinventario')),
                ('mantenimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos', to='users.mantenimiento')),
            ],
            options={
                'verbose_name': 'Dispositivo en Mantenimiento',
                'verbose_name_plural': 'Dispositivos en Mantenimiento',
                'db_table': 'recibe',
                'unique_together': {('mantenimiento', 'dispositivo')},
            },
        ),
    ]
