# Generated by Django 5.2.1 on 2025-06-27 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_alter_dispositivomantenimiento_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispositivoinventario',
            name='id',
        ),
        migrations.AlterField(
            model_name='dispositivoinventario',
            name='numero_inventario',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
